### ISSUE TITLE
Remove `impatient.nvim`

### ISSUE THREAD

**Issue by lucat1** [visimp/visimp#118]
As mentioned in [lewis6991/impatient.nvim](https://github.com/lewis6991/impatient.nvim) it is now deprecated and no longer required for `nvim 0.9+`. We should remove it from the default layer.

**Comment by foxyseta** [comment]
Should we also invoke `vim.loader.enable()` somewhere to replace it?

**Comment by lucat1** [comment]
Yup! I'd say as one of the first things in `setup`

**Comment by foxyseta** [comment]
Cool.

I could open a PR sometime soon, as this does not seem to be super urgent.
