### ISSUE TITLE
nix language layer

### ISSUE THREAD

**Issue by foxyseta** [visimp/visimp#123]
We still need a nix-specific language layer. Out of [the two LSs offered by Mason](https://mason-registry.dev/registry/list?search=language%3Anix+category%3Alsp), I would pick [nil](https://github.com/oxalica/nil), as the other is archived.

Tree-sitter support is available on nvim-treesitter.

**Comment by foxyseta** [comment]
@lucat1 If this is okay with you, I could open a PR

**Comment by lucat1** [comment]
Nil looks good. Feel free to open a PR.
