### ISSUE TITLE
Language server for Typst: move from `typst-lsp` to `tinymist`?

### ISSUE THREAD

**Issue by foxyseta** [visimp/visimp#134]
Typst does not have an official language server.

So far, we have been using [typst-lsp](https://github.com/nvarner/typst-lsp), which has been archived and deprecated on November 5, 2024 in favor of [tinymist](https://github.com/Myriad-Dreamin/tinymist). Tinymist is also available on mason, so the upgrade would appear to be trivial. However, it is not a drop-in replacement, not even config-wise. This is going to be a breaking change.

**Comment by lucat1** [comment]
We can do this trivial change and then bump by one minor version.
